# UI Deployment Pipeline

trigger:
  branches:
    include:
      - master
      - releases/*
  paths:
    include:
      - ui/*
    exclude:
      - api/*

variables:
  S3_BUCKET: exam-tips-ui

stages:
  - stage: Configure
    jobs:
      - job: Setup
        pool:
          vmImage: "Ubuntu-16.04" # defines runtime

  - stage: Linting
    jobs:
      - job: Run_Linting
        steps:
          - script: |
              cd ui/
              npm ci --quiet
              npm run lint
            displayName: "Running Tests"
  - stage: Testing
    jobs:
      - job: Run_Tests
        steps:
          - script: |
              cd ui/
              npm ci --quiet
              CI=true npm run test
            displayName: "Running Tests"

  - stage: Build
    jobs:
      - job: Run_Build
        steps:
          - script: |
              cd ui/
              npm ci --quiet
              GENERATE_SOURCEMAP=false npm run build
            displayName: "Running Tests"
          - task: PublishPipelineArtifact@0
            inputs:
              artifactName: "ui"
              targetPath: "ui/build/"
            displayName: "Publish"
