Transform: "AWS::Serverless-2016-10-31"
Globals:
  Api:
    TracingEnabled: true
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
  Function:
    Runtime: nodejs10.x
    Tracing: Active
    Environment:
      Variables:
        TABLE_NAME: Exam-Tips
        SIGNING_KEY_NAME: SigningKey
Resources:
  # Lambda
  LambdaLocalCorsStub:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/options/
      Handler: index.handler
      Role: arn:aws:iam::867997404618:role/lambda-dynamo-xray
      FunctionName: cors_handler
      Timeout: 30
      Events:
        ClockInOptions:
          Type: Api
          Properties:
            RestApiId: !Ref ExamTipsAPI
            Path: /{cors+}
            Method: OPTIONS

  LoginUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/user/login
      Handler: index.handler
      Role: arn:aws:iam::867997404618:role/lambda-dynamo-xray
      Events:
        TestSetup:
          Type: Api
          Properties:
            RestApiId: !Ref ExamTipsAPI
            Path: /login
            Method: post

  RegisterUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/user/register
      Handler: index.handler
      Role: arn:aws:iam::867997404618:role/lambda-dynamo-xray
      Events:
        TestSetup:
          Type: Api
          Properties:
            RestApiId: !Ref ExamTipsAPI
            Path: /register
            Method: post

  # API
  ExamTipsAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: Exam-Tips
      StageName: dev
      DefinitionBody:
        "Fn::Transform":
          Name: "AWS::Include"
          Parameters:
            Location: s3://exam-tips-builds/swagger-api-template.json
